apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
- name: postgresql
  namespace: voting-dev
  version: 18.1.11
  repo: https://charts.bitnami.com/bitnami
  releaseName: db
  valuesFile: postgres-value.yaml