apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: worker
        image: nahlathabet/worker:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 999
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "800Mi"    
            cpu: "500m"
        env:
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        - name: DOTNET_gcServer
          value: "0"

    
     
