apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    namespace: voting-dev
    version: 23.2.12
    repo: https://charts.bitnami.com/bitnami
    releaseName: redis
    valuesFile: redis-values.yaml
resources:
  - redis-svc.yaml