apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: postgres
            chart: postgresql
            repo: https://charts.bitnami.com/bitnami
            version: 18.1.11
            valuesFile: postgres/postgres-values.yaml
            namespace: voting-dev

          - name: redis
            chart: redis
            repo: https://charts.bitnami.com/bitnami
            version: 23.2.12
            valuesFile: redis/redis-values.yaml
            namespace: voting-dev

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      sources:
        # Helm chart source
        - repoURL: '{{repo}}'
          chart: '{{chart}}'
          targetRevision: '{{version}}'
          helm:
            releaseName: '{{name}}'
            valueFiles:
              - $values/{{valuesFile}}
        
        # Git repo source for values files
        - repoURL: 'https://github.com/NahlaAbdAlghany/voting-app.git'
          targetRevision: 'phase-two'
          ref: values

      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true